### DISCUSSION TITLE
How can I suppress a job if publish isn't happening?

### DISCUSSION THREAD

**Discussion by IPWright83** [changesets/changesets#1106] [Q&A]
The workflow I have set-up currently involves:

- PR is merged into master which triggers a Github workflow
- Changesets runs and creates a new pull request with the version changes (and runs a chromatic job)
- Changesets PR is merged into master which triggers the above Github workflow
- Changesets runs and publishes, and runs the chromatic job again.

Basically the chromatic job, I want to suppress on the first run. It should only ever run, if a publish happens. But I've tried countless ways to disable it and can't get it working. Here's my workflow on my latest attempt:

```
changesets_version:
    needs: [unit]
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    outputs:
      published: ${{ steps.release.published }}
    #   hasChangesets: ${{ steps.release.hasChangesets }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.2.2
        with:
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: pnpm Install
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Release
        id: release
        uses: changesets/action@v1
        with:
          publish: echo "published=true" >> "$GITHUB_OUTPUT" && pnpm run publish
          version: pnpm run version
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

debug_changesets:
    needs: changesets_version
    # if: "needs.changesets_version.outputs.hasChangesets == false"
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: echo "debug_changesets running"
      - run: echo ${{ needs.changesets_version }}
      - run: echo ${{ needs.changesets_version.outputs.published }}
      
update_chromatic_baseline:
    needs: changesets_version
    if: "needs.changesets_version.outputs.hasChangesets == false"
    runs-on: ubuntu-latest
    steps:
        ....
```

You can see with my `debug_changesets` job I'm trying to find what variable I need. I'm currently trying to manually set it which isn't working either. I've tried so many combinations of echoing the value to get correct for my `if` statement, but everything is just null... Here's what I've tried:

- `needs.changesets_version.outputs.published`
- `needs.changesets_version.outputs.hasChangesets`
- `needs.changesets_version.outputs.release.published`
- `needs.changesets_version.outputs.release.hasChangesets`

Can anyone tell me what I need in the `if` to only run this job when a publish happens?
