### DISCUSSION TITLE
What's the best practice when you need to build a package before publishing?

### DISCUSSION THREAD

**Discussion by supersabillon** [changesets/changesets#1136] [Q&A]
If you have package that needs to be built/transpiled with webpack/vite/parcel/rollup etc, what's the best way to do this with Changesets?

My current solution is to:

```
      - name: create PR and/or publish versions
        uses: changesets/action@v1
        with:
          version: pnpm changeset:version
          commit: 'chore: update versions'
          title: 'chore: update versions'
          publish: pnpm release
```

and my release command:
```
"release": "pnpm -F \"./packages/**\" build && pnpm changeset:publish",
```

The drawback here is that im building EVERYTHING under /packages, when perhaps only 1 package might need to publish. Also the command always runs even if they are no packages to publish so I would really wish to keep the scope of the build step super minimal.

The ideal workflow would be to have changeset run a `build` command for only the package we want to publish. Is this possible?
