### DISCUSSION TITLE
Any downsides to triggering releases only on `.changeset/*.md` file changes?

### DISCUSSION THREAD

**Discussion by moltar** [changesets/changesets#1224] [Ideas]
I do not see this being the recommended course of action, so I am thinking maybe I am missing something.

Why would this not work in a GitHub action:

```yml
name: Release
on:
  push:
    branches:
      - master
    paths:
      - .changeset/*.md
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:

```

See: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
