### DISCUSSION TITLE
How to version a private project

### DISCUSSION THREAD

**Discussion by rawand-faraidun** [changesets/changesets#1312] [Q&A]
I have a private project and versioning is so important for me and it is not for npm, I configured changeset to make the changelog and handle the versioning, but it does not make Github releases, here is my configuration

It makes the right pull requests for the versioning everytime i have a changeset markdown, but the problem is as i said the github release is not made
![image](https://github.com/changesets/changesets/assets/62562422/e5c63173-a29e-42ac-8889-db3573c70c50)
![image](https://github.com/changesets/changesets/assets/62562422/b5f008b4-8b7c-4104-a791-15bb190029f0)

`.changeset/config.json`:
```json
{
  "$schema": "https://unpkg.com/@changesets/config@3.0.0/schema.json",
  "changelog": "@changesets/cli/changelog",
  "commit": false,
  "fixed": [],
  "linked": [],
  "access": "restricted",
  "baseBranch": "main",
  "updateInternalDependencies": "patch",
  "ignore": []
}
```

`.github/workflows/release.yml`
```yml
name: Release
on:
  push:
    branches:
      - "main"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

and here is my `release` script: `pnpm run ci && changeset version`

And lastly here is my action workflow permissions
![image](https://github.com/changesets/changesets/assets/62562422/c7e79542-d0d2-4ac1-a776-02061d631680)

**Comment by cyrfer** [comment]
@rawand-faraidun I have private packages working, but it was difficult to set up. What do you see in the logs of your action?

I am using Github Packages for my private registry. For Github Packages, I remember I needed to carefully specify the `repository` field in my package.json files. Mine looks like:

```json
  "repository": {
    "type": "git",
    "url": "git+https://github.com/ORGNAME/REPONAME.git"
  },
```

Here is my `step`. Notice the use of `release` and not `version` like you showed.
This might not be the solution, but I do get releases. I am happy to look for more settings.

```yaml
      - name: Run Changesets
        id: changesets
        uses: changesets/action@v1
        with:
          # Call our release script which is defined in the main package.json
          publish: npm run release
          # Here's what the release script actually does.
          # publish: npm run build-all && npx changeset publish
        env:
          # Changesets needs our Github token. We pass it in an environment variable. 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

My config is probably similar to yours.

```json
{
  "$schema": "https://unpkg.com/@changesets/config@2.2.0/schema.json",
  "changelog": "@changesets/cli/changelog",
  "commit": false,
  "fixed": [],
  "linked": [],
  "access": "restricted",
  "baseBranch": "main",
  "updateInternalDependencies": "patch",
  "ignore": []
}
```

I do have a problem that I still need to solve. I think the releases occur when merging to main from my FEATURE branches. I think the version bumps and releases should only occur after merging the VERSION branch to main.
