### DISCUSSION TITLE
How to setup meaningful commit messages?

### DISCUSSION THREAD

**Discussion by IlyaSemenov** [changesets/changesets#1339] [Q&A] [answered]
Currently, changesets commits with message "Version Packages" which doesn't exactly make sense. I would like the messages to be more meaningful, like _"build: my-package@1.2.3"_ (or multiple packages in monorepo).

I know I can set `title` in `config.json` (as suggested [here](https://github.com/changesets/changesets/issues/246#issuecomment-1214255887)), but that will still be static message, not dynamic. What am I missing?

**Comment by nadjiel** [comment]
I am also facing this issue. I want to include the version created in the commit message and PR title, but, at least to my knowledge, the version number can only be obtained after the Changeset Action finishes, like I do in the final line of the code below:

```yml
# Uses package.json scripts to create a version PR or build a release
- name: Create Release Pull Request or Publish
  id: changesets
  uses: changesets/action@v1
  with:
    version: npm run version
    publish: npm run publish
    commit: ":rocket: release: created new release"
    title: Created new release
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Gets version tag if created
- name: Get version
  id: get-version-tag
  if: steps.changesets.outputs.published == 'true'
  run: echo "version_tag=v${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}" >> $GITHUB_OUTPUT
```

Were you able to find any solutions @IlyaSemenov?

**Comment by mikededo** [comment, marked as answer]
If you want something dynamic, you could create an ENV variable like: 

```yaml
      - name: Capture new release versions # Create a step that fits your needs
        run: |
          bun changeset status --output=release.json
          # This outputs something like: packageOne@x.y.z, packageTwo@x.y.z
          echo "CHANGED_PACKAGES=$(jq -r '.releases | map(.name + "@" + .newVersion) | join(", ")' release.json)" >> "$GITHUB_ENV"
          rm release.json
      - name: Create PR release or publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: bun changeset version
          publish: ./release.sh
          commit: 'chore(release): ${{env.CHANGED_PACKAGES}}' # Then I can use the ouput
          title: 'chore(release): ${{env.CHANGED_PACKAGES}}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
```

In this example, which is what I use in my monorepo, it allows me to get all the updated packages. In your case, you could create a script (even using `ts` and running it with node/bun/deno) that would output something. You can then store this in an `env` of the running action and use it in the commit and/or title.

**Reply by nadjiel** [reply]
Thanks for the tip! It worked for me with a few adaptations to prevent the workflow of failing in case the `changeset status` command does. Now I'm getting dynamic messages depending on the version.

```yml
# Get new release versions in format "packageOne@x.y.z, packageTwo@x.y.z"
- name: Get new versions
  run: |
    npx @changesets/cli status --output=release.json || true

    if [ ! -f "release.json" ]; then
      exit 0
    fi
          
    echo "CHANGED_PACKAGES=$(jq -r '.releases | map(.name + "@" + .newVersion) | join(", ")' release.json)" >> "$GITHUB_ENV"

    rm release.json
```

![Image showing how the PR title and commit looks like.](https://github.com/user-attachments/assets/f3056984-e7ea-4cc2-9bcc-be20c97a6e95)

**Reply by mikededo** [reply]
Glad it helped!

**Reply by IlyaSemenov** [reply]
Thank you, this worked. Considering @nadjiel comments, the complete solution I ended up with:

```yaml
env:
  MAIN_REF: refs/heads/master

jobs:
  test-and-release:
    name: Test and Release
    runs-on: ubuntu-latest

    steps:
      # checkout, build and test, then:

      - name: Capture new release versions
        if: ${{ github.ref == env.MAIN_REF }}
        run: |
          if pnpx @changesets/cli status --output=release.json; then
            echo "CHANGED_PACKAGES=$(jq -r '.releases | map(.name + "@" + .newVersion) | join(", ")' release.json)" >> "$GITHUB_ENV"
            rm release.json
          fi

      - name: Create Release Pull Request or Publish to npm
        if: ${{ github.ref == env.MAIN_REF }}
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish
          title: 'Release ${{env.CHANGED_PACKAGES}}'
          commit: 'Release ${{env.CHANGED_PACKAGES}}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```
