### DISCUSSION TITLE
How to upload additional release assets after successful publication?

### DISCUSSION THREAD

**Discussion by bofomike** [changesets/changesets#1366] [Q&A]
I'm working on SDK that expose UI components that could be used by integrators. 

After successful github release and publication to npm, I would like to upload built distribution index.css file into github release (assets), so it could be linked/imported by others. 
(I don't want to include it into src zip file, I would like to upload css file separately in raw form)

Is it possible to configure changesets to do so? 

If not, is there any other action I could easily use?
I was looking into `actions/upload-release-asset@v1` but didn't figure how to use it smoothly after changesets action...

Here's how I use changesets action at the moment:
```
      ...
      - run: pnpm install

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish index.css
        uses/run: ... // TODO upload built ./dist/css file here
```

Best,
~Mike 🫡
