### DISCUSSION TITLE
How to add artifacts to the release?

### DISCUSSION THREAD

**Discussion by Dwarf1er** [changesets/changesets#1503] [Q&A]
I'm working on a monorepo using Turborepo, which includes a VSCode extension and several packages that I publish to NPM. While publishing to NPM works flawlessly, I'm facing challenges adding the .vsix file of my VSCode extension to the GitHub release created by the Changesets GitHub Action.

I've tried using both `svenstaro/upload-release-action@v2` and `xresloader/upload-to-github-release@v1` to upload the VSIX file as an asset to the release (as suggested [here](https://github.com/changesets/changesets/discussions/1086)). However, both actions seem to overwrite the release created by the Changesets action, resulting in only the VSIX file being uploaded and losing other artifacts (like the standard ZIP files).

Here's what I attempted:
```yaml
            - name: Get New VSCode Extension changeset
              run: |
                  changeset_files=$(find .changeset -name '*.md')
                  found=false

                  for file in $changeset_files; do
                    if grep -q "sqlanydb-tools-vscode" "$file"; then
                      found=true
                      break
                    fi
                  done

                  if [ "$found" = true ]; then
                    echo "VSCODE_CHANGED=true" >> $GITHUB_ENV
                  else
                    echo "VSCODE_CHANGED=false" >> $GITHUB_ENV
                  fi

            - name: Create Release Pull Request or Publish to npm
              id: changesets
              uses: changesets/action@v1
              with:
                  publish: npm run release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Package VSCode Extension
              if: env.VSCODE_CHANGED == 'true'
              run: |
                  cd ./apps/sqlanydb-tools-vscode
                  npm run package-vsix

            - name: Upload VSIX to Release
              if: env.VSCODE_CHANGED == 'true'
              uses: xresloader/upload-to-github-release@v1
              with:
                  file: ./apps/sqlanydb-tools-vscode/sqlanydb-tools-vscode-*.vsix
                  tags: false
                  update_latest_release: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and Publish VSCode Extension
              if: env.VSCODE_CHANGED == 'true'
              run: |
                  cd ./apps/sqlanydb-tools-vscode
                  npm run publish
              env:
                  VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
```
