### DISCUSSION TITLE
Using `on.push.paths` instead of `on.push.branch`?

### DISCUSSION THREAD

**Discussion by harshcut** [changesets/changesets#850] [Q&A] [answered]
What could be some undesired side effects of using `on.push.paths` instead of `on.push.branch` in github actions for publishing package to NPM? To my experience, the `CHANGELOG.md` file is generated only when a package is ready for release.

```yml
on:
  push:
    branches:
      - main
    paths:
      - 'packages/**/CHANGELOG.md'
```
