### DISCUSSION TITLE
`changeset status` as CI in the Version Packages PR itself

### DISCUSSION THREAD

**Discussion by glasser** [changesets/changesets#912] [Q&A] [answered]
Hi! I recently added a `changeset status` command to our CI to ensure that any PRs that change packages either have a changeset or are explicitly marked as non-changeset-worthy with `changeset --empty`.

One problem I'm running into is that the "Version Packages" fails this CI! I'm seeing this right now on a `pre` branch but a quick manual test shows that this happens in normal cases too. Presumably this is because there are (correctly) no changesets left on the branch but it is different from the base branch (bumping all the versions and editing the CHANGELOGs).

Surely this is something folks have run into before? What do people do about this? Detect that it's a Version Packages branch (eg looking at the name of the current HEAD commit or something) or something?

(I do recognize that using `changelog status` in CI is not recommended by the docs, but presumably some people do use it successfully...)

**Comment by glasser** [comment, marked as answer]
Ah, I see that the changeset bot checks to see if the ref starts with `changeset-release`. That seems reasonable!

**Reply by Andarist** [reply]
I think this answers the question and this is what I would do today. If you think that we could somehow improve the situation around this you could always also open an issue about it, preferably with a proposal of how this could be improved at the behavioral/implementation level.

**Reply by glasser** [reply]
This is what I got working on CircleCI specifically. Note that `setup-node` is a custom command in our config.yml. I wanted to make the job as fast as possible if we're on a release branch, so I skipped all the setup steps, but then added a little `echo` step because otherwise CircleCI got sad that there were no steps in the job. (I didn't skip the job entirely because otherwise you can't require the job to pass in GitHub.)

```
  Changesets:
    docker:
    - image: cimg/base:stable
    steps:
      - run: echo Ensure there is at least one step
      - unless:
          condition:
            matches:
              pattern: "^changeset-release/.+$"
              value: << pipeline.git.branch >>
          steps:
            - setup-node
            - run: npm run changeset-check
```
