### ISSUE TITLE
is there a way to do nighly / unstable releases?

### ISSUE THREAD

**Issue by NullVoxPopuli** [changesets/changesets#1091]
## Affected Packages

Idk

## Problem

I may not be ready for a release, but i may want folks to be able to test out changes without manually doing pre-reloason

## Proposed solution

Provide an unstable option in config. When true, every merge is published (provided the changesets declare changes) with the git sha appended to the version. This uses the 'unstable' tag on npm, and does not create github releasen, nor remove the changeset files

**Comment by NullVoxPopuli** [comment]
yeah, for unstable releases, I wouldn't care about noting changelog entries -- I (and I'm sure a good number of folks) review their changelog / changesets before actual release, proofread, etc etc -- all unneeded for unstable

**Comment by jake-slashid** [comment]
I would also really like this feature. When the changeset publish PR opens (and each time it updates) an unstable version should be published.

Currently to do integration testing when multiple changesets come together we have to manually publish versions or use workarounds like links and `yalc`.

**Comment by jake-slashid** [comment]
For now we've implemented this ourselves with a github action

```
name: Unstable/nightly release

on:
  push:
    branches: [main]

jobs:
  unstable-release:
    name: Unstable/nightly release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4

      - name: Use Node.js 16.14.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.0
          cache: "pnpm"
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Generate unstable changeset
        run: pnpm changeset version --snapshot next
        
      - name: Build packages
        run: pnpm build
        
      - name: Publish unstable packages
        run: pnpm changeset publish --tag next
```
