### ISSUE TITLE
Github release but don't publish to npm - github actions ci cd

### ISSUE THREAD

**Issue by AlexandrosMelissas** [changesets/changesets#1111]
## Problem
I have a monorepo where i need to make a github release but not publish npm. To achieve the "not publish part", i have changed every package package.json to have `private: true`. The problem now is that every time i merge the PR of changeset bot to main, i get this output in the workflow. I am assuming this is why github release is not getting triggered. This was triggered when i merged the changesets bot pr:

```
Run changesets/action@v1
setting git user
/usr/bin/git config user.name "github-actions[bot]"
/usr/bin/git config user.email "github-actions[bot]@users.noreply.github.com"
setting GitHub credentials
No changesets found, attempting to publish any unpublished packages to npm
No user .npmrc file found, creating one
/home/runner/setup-pnpm/node_modules/.bin/pnpm release

> house-manager-monorepo@1.0.0 release /home/runner/work/house-manager-mono/house-manager-mono
> changeset publish

🦋  warn No unpublished projects to publish
/usr/bin/git push origin --tags
Everything up-to-date
```

This is the output when i merged my actual changes with the changeset in order to trigger bot pr:
```
Run changesets/action@v1
setting git user
/usr/bin/git config user.name "github-actions[bot]"
/usr/bin/git config user.email "github-actions[bot]@users.noreply.github.com"
setting GitHub credentials
/usr/bin/git checkout changeset-release/main
error: pathspec 'changeset-release/main' did not match any file(s) known to git
/usr/bin/git checkout -b changeset-release/main
Switched to a new branch 'changeset-release/main'
/usr/bin/git reset --hard 36bf061f1f2733919643256e964c68ce2edfaf7d
HEAD is now at 36bf061 changed dockerifle
/opt/hostedtoolcache/node/16.19.1/x64/bin/node /home/runner/work/house-manager-mono/house-manager-mono/node_modules/.pnpm/@changesets+cli@2.26.0/node_modules/@changesets/cli/bin.js version
🦋  All files have been updated. Review them and commit at your leisure
/usr/bin/git status --porcelain
 D .changeset/beige-spiders-retire.md
 M apps/api/CHANGELOG.md
 M apps/api/package.json
/usr/bin/git add .
/usr/bin/git commit -m Version Packages
[changeset-release/main 0d0c11f] Version Packages
 3 files changed, 7 insertions(+), 6 deletions(-)
 delete mode 100644 .changeset/beige-spiders-retire.md
/usr/bin/git push origin HEAD:changeset-release/main --force
To https://github.com/AlexandrosMelissas/house-manager-mono
   7b1a06b..0d0c11f  HEAD -> changeset-release/main
{
  "total_count": 0,
  "incomplete_results": false,
  "items": []
}
creating pull request

```

This is my release yml:

```
name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: true

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
## Proposed solution

I've got no clue. All i want is to make a github release without publishing to npm.
