### ISSUE TITLE
Version not updated in package-lock.json

### ISSUE THREAD

**Issue by tpluscode** [changesets/changesets#1139]
## Affected Packages

Don't know

## Problem

When using npm, running `changeset version` does not update the version in the lock file. 

This does not appear to have any ill effect and may be purely cosmetic

## Proposed solution

Running `npm install` ensures that the version is updated

**Comment by sscaff1** [comment]
I think this is purely cosmetic as you said, but I'm curious if any package maintainers here have any input on this.

**Comment by almahdi404** [comment]
But running `npm install` also tries to update dependencies.

**Comment by almahdi404** [comment]
Until [#1455](https://github.com/changesets/changesets/pull/1455) gets merged.

```json
{
  "scripts": {
     "v": "changeset version && npm i synclockver --no-save && synclockver",
     "release": "npm ci && npm run build && changeset publish",
  }
}
```
```yml
- name: Create Release Pull Request or Publish to NPM
  uses: changesets/action@v1
  with:
    version: npm run v
    publish: npm run release
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```
