### ISSUE TITLE
Add support for publishing with provenance

### ISSUE THREAD

**Issue by danez** [changesets/changesets#1152]
## Affected Packages

cli probably

## Problem

npm has introduced provenance https://docs.npmjs.com/generating-provenance-statements
pnpm as of version 8.4 also supports it.

The question it how to implement it to keep supporting older clients. Either it is a config option, or autodetection of the client version and always enable it. Although not sure if it should be always enabled.

**Comment by odanado** [comment]
You can support provenance in publishing without changing the `@changesets/cli`.

As described in [Using third-party package publishing tools](https://docs.npmjs.com/generating-provenance-statements#using-third-party-package-publishing-tools), simply add `"provenance": true` to the `publishConfig` in `package.json`.

`sigstore/sigstore-js` supports provenance in this way.
ref: [package.json](https://github.com/sigstore/sigstore-js/blob/1cee5b5aca76c7169d07ac10752c47000758e3c9/package.json#L25C1-L27)

**Comment by uiolee** [comment]
Seconded

**Comment by aromko** [comment]
Hello. Can someone confirm that the provenance flag works with adjusting the package.json? I tried it with https://docs.npmjs.com/generating-provenance-statements#example-github-actions-workflow but it leads to permission denied error on the repo.

**Comment by mscharley** [comment]
It works for me:

* [example #1](https://www.npmjs.com/package/@mscharley/dot)
* [example #2](https://www.npmjs.com/package/generic-type-guard)

**Comment by rygine** [comment]
i'm still having trouble publishing with provenance after updating the `publishConfig` of the root `package.json`, adding a `.npmrc` file, and a GH actions `NPM_CONFIG_PROVENANCE` environment variable. the GH release workflow also has the proper permissions.

the repo uses yarn, but i'm not sure that matters as changesets [still uses NPM](https://github.com/changesets/changesets/blob/main/packages/cli/src/commands/publish/npm-utils.ts#L191-L197) to publish.

link to repo: https://github.com/xmtp/snap

perhaps an explicit option would solve this? (e.g. `changeset publish --provenance`)

**Comment by aromko** [comment]
Hey. The problem still exists in our repo. So we also use node 18.x. Maybe that's the problem. I will try it again if we do a update.

**Comment by Andarist** [comment]
I'd like to support this but nobody has provided a PR implementing this that I could review. Unfortunately, my life is currently packed with other things and I just don't feel drawn to Changesets enough to work on it in my free time for free. Don't take me wrong - I love the project. There are just so many hours in a day though and I have to pick up my priorities.

I'd be willing to work on this but the work would have to get sponsored.

**Comment by benmccann** [comment]
Here's an example PR showing how to do it: https://github.com/sveltejs/kit/pull/12567

One thing that would be nice is if changesets let you set provenance for the whole repo in an easier fashion vs having to set `"publishConfig": { "provenance": true }` on every individual package

**Comment by Andarist** [comment]
It can also be set up this way: https://github.com/changesets/ghcommit/pull/30/files

**Comment by Andarist** [comment]
We support `.changeset/config.json#access` so perhaps, for convenience, we could also support `.changeset/config.json#provenance`. In v3 both could be moved to `.changeset/config.json#publishConfig`

**Comment by JoCa96** [comment]
Since a few days [npm trusted publishing with OIDC is generally available](https://github.blog/changelog/2025-07-31-npm-trusted-publishing-with-oidc-is-generally-available/) and none of the provenance flags is necessary anymore.

See also: https://docs.npmjs.com/trusted-publishers

**Comment by JounQin** [comment]
For trusted publisher: set env `NPM_TOKEN: ''` is the workaround

**Comment by dominikg** [comment]
related: https://github.com/changesets/action/issues/515

**Comment by sonofmagic** [comment]
> For trusted publisher: set env `NPM_TOKEN: ''` is the workaround对于受信任的发布者：设置 env `NPM_TOKEN： ''` 是解决方法
**Thanks @JounQin ! **

And I have a question:
if I add a new subpackage in a monorepo, and other packages depend on it, will this cause the release to fail?
Because at that point the npm token is no longer available, but the new subpackage hasn’t been set up with a Trusted Publisher yet?

**Comment by targetlucked69** [comment]
> [@targetlucked69](https://github.com/targetlucked69) If you're also using GitHub Actions: adding `registry-url: https://registry.npmjs.org` input to `actions/setup-node` resolved the same issue for me ([see my working setup here](https://github.com/andreww2012/eslint-config-un/tree/dev-v1/.github)). By the way, I didn't event have to set `NPM_TOKEN` to an empty string.

I checked your package on NPM and I dont see any `Provenance` section added by NPM? Like this

<img width="802" height="210" alt="Image" src="https://github.com/user-attachments/assets/00534588-fb7d-45b4-847a-a1395ddcd802" />

is that expected?

This is now the error I am getting after adding registry-url:

```bash
🦋  info Publishing "my-package" at "1.2.0"
🦋  error an error occurred while publishing my-package: E404 Not Found - PUT https://registry.npmjs.org/my-package - Not found 
🦋  error 'my-package@1.2.0' is not in this registry.
🦋  error 
🦋  error Note that you can also install from a
🦋  error tarball, folder, http url, or git url.
🦋  error npm notice Publishing to https://registry.npmjs.org/ with tag latest and public access
🦋  error npm error code E404
🦋  error npm error 404 Not Found - PUT https://registry.npmjs.org/my-package- Not found
🦋  error npm error 404
🦋  error npm error 404  'my-package@1.2.0' is not in this registry.
🦋  error npm error 404
🦋  error npm error 404 Note that you can also install from a
🦋  error npm error 404 tarball, folder, http url, or git url.
🦋  error npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2025-11-30T19_30_34_334Z-debug-0.log
🦋  error 
🦋  error packages failed to publish:
🦋  my-package@1.2.0
```

(note `my-package` there is a placeholder)

**Comment by andreww2012** [comment]
@targetlucked69 I'm using trusted publishing which has provenance by default

You probably don't see it because I only published pre-releases with TP

**Comment by targetlucked69** [comment]
> [@targetlucked69](https://github.com/targetlucked69) I'm using trusted publishing which has provenance by default
> 
> You probably don't see it because I only published pre-releases with TP

<img width="732" height="217" alt="Image" src="https://github.com/user-attachments/assets/4195c92d-61a5-427b-896a-e16a10e6e4f0" />

do you have the same setting? I believe OIDC accepts this either way

**Comment by Shurtu-gal** [comment]
Even for us none of the suggested solutions seem to work. Latest run: https://github.com/asyncapi/cli/actions/runs/20265856000/job/58189340320

Logs:
```logs
🦋  info npm info @asyncapi/cli
🦋  info @asyncapi/cli is being published because our local version (5.0.0) has not been published on npm
🦋  info Publishing "@asyncapi/cli" at "5.0.0"
🦋  error an error occurred while publishing @asyncapi/cli: ENEEDAUTH This command requires you to be logged in to https://registry.npmjs.org 
🦋  error You need to authorize this machine using `npm adduser`
```

**Comment by Zehir** [comment]
For peoples comming here next looking for a solution I was able to make it work by using;

The changes from previous CI was: 
- Adding permissions
- Adding a npm update (Update npm step)
- Set NPM_TOKEN to ''
- Set NPM_CONFIG_PROVENANCE to true

Here a full example :
```yaml
name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Update npm
        run: npm update -g npm

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ''
          NPM_CONFIG_PROVENANCE: true
```

**Comment by openscript** [comment]
Also keep in mind that `id-token` is not available on `pull_request_target`. So I usually do something like:


```
name: Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  publish:
    if: contains(github.event.head_commit.message, 'publish new release')
...
```
