### ISSUE TITLE
cant publish new version from within a github action

### ISSUE THREAD

**Issue by valiantlynx** [changesets/changesets#1262]
## Affected Packages

@valiantlynx/tsconfig

## Problem

i have a simpe package everthing works fine locally including publishing. the problem is when i push it to github. and the action starts it fails with this error:
info npm info @valiantlynx/tsconfig
🦋  info @valiantlynx/tsconfig is being published because our local version (0.0.10) has not been published on npm
🦋  info Publishing "@valiantlynx/tsconfig" at "0.0.10"
🦋  error an error occurred while publishing @valiantlynx/tsconfig: E404 Not Found - PUT https://registry.npmjs.org/@valiantlynx%2ftsconfig - Not found 

the error is technically an npm error. i get 404 that the package is not in npm but, of course its not, im trying to upload it.

## Proposed solution

ive been stuck on this for some time and i dont know where to start. i was just trying random shit.:

here is my github action very standard:
```yaml 
---
# This workflow will release the packages with Changesets

name: 🚀 CI - publish

on:
  push:
    branches:
      - 'valiantlynx-turborepo'
  workflow_dispatch:
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

and this is my package.json :

```json
{
  "name": "@valiantlynx/tsconfig",
  "version": "0.0.9",
  "license": "MIT",
  "files": [
    "dist"
  ],
  "scripts": {
    "build": "rm -rf dist && mkdir dist && cp base.json nextjs.json react-library.json ts-library.json svelte.json noentry.js dist/",
    "changeset": "changeset",
    "publish:packages": "changeset publish",
    "version:packages": "changeset version",
    "release": "yarn version:packages && yarn publish:packages"
  },
  "publishConfig": {
    "access": "public"
  },
  "main": "dist/noentry.js",
  "devDependencies": {
    "@changesets/cli": "^2.26.2"
  }
}
```
