### ISSUE TITLE
Ability to add version to commit message and pull request?

### ISSUE THREAD

**Issue by nooblyf** [changesets/changesets#1427]
## Affected Packages

`pkg:@changesets/cli`
`pkg:@changesets/action`

## Problem

Ability to access version when creating pull request via GitHub action? In order to make pull request title something like "chore(release): v1.2.3"

## Proposed solution

I know the commit message and pull request title can be modified but if there's a `__VERSION__` we could use to let the action know to inject the current version at that place, that should work
```yml
with:
  commit: "chore(release): v__VERSION__"
  title: "chore(release): v__VERSION__"
  version: changeset version
```

So, this would create a pull request and commit message "chore(release): v1.2.3" if version is `1.2.3`
