### ISSUE TITLE
Failed to find where HEAD diverged from "origin/main" with > 22 commits in feature branch

### ISSUE THREAD

**Issue by cefn** [changesets/changesets#1558]
## Affected Packages

@changesets/cli

## Problem

As far as I can make out when there are too many commits on a feature branch, (recently demonstrated with 22) the logic of finding the branch point is failing for some reason. Until I squash commits down to a smaller number I get...

```
error Error: Failed to find where HEAD diverged from "origin/main". Does "origin/main" exist and it's synced with remote?
```

Squashing multiple commits by running `git rebase -i $(git merge-base origin/HEAD main)` and choosing `squash` for commits after the first `pick` seems to resolve the issue, and the cli can find the branch point again.

## Proposed solution

If there's some explicit traversal and a limit on the number of hops which the traversal takes, this limit should be controllable or much larger

Given `git merge-base origin/HEAD main` is able to find the fork point, and changesets has a git adaptor, perhaps the logic should consume the commit from that git command?

**Comment by cefn** [comment]
This turned out to be coupled to our Gitlab pipelines. 

By default there's a clone depth of a tested commit of just 20 'steps' away from the commit. Consequently if you look for 'main' and it's more than 20 commits away it has 'disappeared' from the point of view of the pipeline.

If you are in gitlab see `Settings => CI/CD => General Pipelines`

![Image](https://github.com/user-attachments/assets/8dbaca60-20bd-4342-8926-a02bdd43e99b)

**Comment by ben-xD** [comment]
I don't think the solution here is to just configure Gitlab to `git clone`. Gitlab does this as optimisation, and we'd be disabling that. Some repos are too big for their own good 😂

What I've done instead is:
```yaml
changesets:
  extends: lint
  script:
    # Fetch the branch before trying to reference it, otherwise we'd get an error with `git log main` or `git merge-base` because of Gitlab's optimisations. See https://github.com/changesets/changesets/issues/1558#issuecomment-2627252153
    - git fetch origin main
    - git merge-base origin/main HEAD
    - pnpm changeset status
```
