### ISSUE TITLE
Configure the PR title generated by the changesets action

### ISSUE THREAD

**Issue by timleslie** [changesets/changesets#266]
## Problem

A recent change to the changesets action meant the title of the generated PR was changed. This was very confusing at first, and will require me to update our release process docs to reflect the new name.

I would like to be able to configure the generated PR's title so that a) it says what I want and b) doesn't randomly change without notice.

This is a low priority, nice to have issue from my POV 👍

**Comment by Noviny** [comment]
Aside, the PR title name got reverted, which I would argue makes this lower priority.

**Comment by mihkeleidast** [comment]
Randomly came across this issue - it does seem like it is possible to configure this, so maybe this issue can be closed. https://github.com/changesets/action#inputs

**Comment by trivikr** [comment]
> it does seem like it is possible to configure this

As per the docs, it's possible to configure this using `commit` and `title` fields on input.

**Comment by aalv1234** [comment]
> 

where in the docs is this specified?

**Comment by bluwy** [comment]
Yeah it looks like this can be configured now:


```yaml
      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          title: "chore: release"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
