### ISSUE TITLE
Error with GitHub registery

### ISSUE THREAD

**Issue by JulienKode** [changesets/changesets#650]
## Error with GitHub registery

I have the following .yarnrc.yml

```yml
enableImmutableInstalls: false

nodeLinker: node-modules

npmScopes:
  xxx-xxx:
    npmAuthToken: "${GITHUB_TOKEN-''}"
    npmPublishRegistry: "https://npm.pkg.github.com/"
``` 

Here is the CI that I have ("translated" into GitHub Actions, I use another CI than Github)
```yml
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - XXXX

      - run: yarn install --immutable

      - run: 'yarn changeset version && yarn config set enableImmutableInstalls false && yarn install && git add yarn.lock && git commit -m "chore: update lockfile [skip-ci]" && git push --set-upstream origin master'

      - run: yarn changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

The last command `yarn changeset publish` fail with the following error:
```
🦋  error Received an unknown error code: E401 for npm info "@xxx-xxx/test-publish"
🦋  error Unable to authenticate, need: Basic realm="GitHub Package Registry"
error Command failed with exit code 1.
```

When I use `yarn npm publish` instead I can publish the package,
Did you have any idea how I can fix the issue or understand why we have it
