### ISSUE TITLE
Unable to publish private package

### ISSUE THREAD

**Issue by robphoenix** [changesets/changesets#739]
## Affected Packages

- `@changesets/cli`
- `@changesets/action`

## Problem

I get a 404 when trying to publish a private package with Github Actions.

<details>
  <summary>Error message</summary>

```
🦋  error an error occurred while publishing @org-name/ui-design-tokens: E404 Not Found - PUT https://registry.npmjs.org/@org-name%2fui-design-tokens - Not found 
```

</details>

<details>
  <summary>Changesets config</summary>

```json
{
  "commit": false,
  "access": "restricted",
  "baseBranch": "main",
  "updateInternalDependencies": "patch",
  "ignore": []
}
```

</details>

<details>
  <summary>Package settings on NPM</summary>

![image](https://user-images.githubusercontent.com/9257284/150126437-2520a6da-a0c9-4eb4-8ba9-49029901458b.png)

</details>

<details>
  <summary>Example package.json for package to be published</summary>

```json
{
  "name": "@org-name/ui-design-tokens",
  "version": "1.0.1",
  "description": "Design Tokens",
  "main": "dist/index.js",
  "scripts": {
    "clean": "rm -rf dist/",
    "build": "yarn run clean && tsc",
    "watch": "yarn run build -- --watch",
    "format": "prettier --write \"./src/**/*.ts\"",
    "lint": "eslint ./src --fix --ext .ts",
    "format:ci": "prettier --list-different \"./src/**/*.ts\"",
    "lint:ci": "eslint ./src --ext .ts",
    "precommit": "lint-staged"
  },
  "lint-staged": {
    "*": [
      "yarn lint",
      "yarn format"
    ]
  },
  "license": "ISC",
  "publishConfig": {
    "access": "restricted"
  },
  "files": [
    "dist",
    "src"
  ]
}
```

</details>

<details>
  <summary>Github Actions release workflow file</summary>

```yaml
name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can
          # generate changelogs with the correct commits
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
          cache-dependency-path: |
            package.json
            'packages/**/package.json'

      - run: yarn install:ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        uses: changesets/action@v1
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```
</details>

The package has been previously published on NPM via a different method, and I have been able to publish the package manually running `yarn changeset publish` locally.
I've looked through the issues and the only similar issue I can find is [this one](https://github.com/changesets/changesets/issues/338#issuecomment-928541501)
I can see it's failing with the 404 on the `PUT` because the package is private in NPM, this doesn't fail if I set it to public. However my assumption was that if I provide the relevant `NPM_TOKEN` then changesets would be able to publish a private package to npm? Is there a reason `changesets publish` is doing the `PUT` when it shouldn't be, maybe I've overlooked a config setting or something?

**Comment by robphoenix** [comment]
🎉  found the issue, it looks like it was to do with the `setup-node` action. I needed to include the `NODE_AUTH_TOKEN`:

```yaml
      - name: Publish to npm
        uses: changesets/action@v1
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```

These issues helped:
- https://github.com/actions/setup-node/issues/82
- https://github.com/tabhero/svelte-components/issues/1

I'll close this, but is this worth documenting somewhere in this repo?
