### ISSUE TITLE
[Question] GITHUB_TOKEN environment variable

### ISSUE THREAD

**Issue by shinokada** [changesets/changesets#940]
When I run `npx changeset version` I get the following error.

I can create a GitHub personal access token. Where can I add it as the GITHUB_TOKEN environment variable?

> ❯ npx changeset version
> The following error was encountered while generating changelog entries
> We have escaped applying the changesets, and no files should have been affected
> 🦋  error Error: Please create a GitHub personal access token at https://github.com/settings/tokens/new and add it as the GITHUB_TOKEN environment variable

**Comment by Andarist** [comment]
It depends where you run `npx changeset version`. If you are using it with our https://github.com/changesets/action then please take a look into its documentation to see the examples of how `GITHUB_TOKEN` can be provided to the action. If you are using this manually on your local machine then this should do the trick:
```sh
GITHUB_TOKEN=t0k3n npx changeset version
```

**Comment by shinokada** [comment]
Thank you for your reply. I'm new to changesets and I'm grateful to get any help.

Following this [doc](https://github.com/changesets/changesets/blob/main/docs/automating-changesets.md#recommended-automation-flow), I installed Github App changeset-bot. And it tells to Add the [github action](https://github.com/changesets/action) to your repository.

Do I need to run `npm i -D changesets/action`  or a file?

**Comment by shinokada** [comment]
Thank you for your help.

This worked:

```
# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branhes: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm i

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: install
        run: npm install

      - name: Create Release Pull Request or Publish to npm
        # https://github.com/changesets/action
        uses: changesets/action@v1
        with:
          # this expects you to have a script called release which does a build for your packages and calls changeset publish
          # my release & version-packages:
          # "release": "npm run build && changeset publish",
          # "version-packages": "changeset version && npm run prettier"
          publish: npm run release
          version: npm run version-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

**Comment by shinokada** [comment]
Ok, I merged the PR and it updated the version and the Changelog.md.

**Comment by shinokada** [comment]
How can I publish the new version to NPM?
Since after merging the PR, the repo version bumps up.

Do I need to create another workflow to run `build` and `publish`?

```
- name: build
        run: npm run build
      - name: publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
```
