### ISSUE TITLE
[Question] Is there a way to publish only changed apps?

### ISSUE THREAD

**Issue by jsanes** [changesets/changesets#956]
## Problem

I have two apps in my monorepo and when any of them changes, everything gets published. I'm using the GitHub action:

```
- name: Create Release Pull Request
  id: changesets
  uses: changesets/action@v1
  with:
    publish: yarn release
```

The command `yarn release` publishes all apps.

Is there a way to divide the publish section and trigger them depending on the changed apps?

If I only change app A, app A will be released, not app B.
