### ISSUE TITLE
Question: Am I missing something trying to create tags?

### ISSUE THREAD

**Issue by IPWright83** [changesets/changesets#972]
Sorry, I've got a question rather than a bug, as I can't work out why this isn't working. I'm trying to generate tags and push them (using pnpm to publish).

Am I doing something wrong here, as every time I end up with no tags in the repo?

![Screenshot_20221005-210153](https://user-images.githubusercontent.com/1374775/194153617-4b991989-360e-4cc4-895a-00bccbc99eb4.png)

**Comment by Andarist** [comment]
The logs look OK so a further investigation would have to be done on your side. I would start by adding `git tag` after `pnpm changeset tag` - just to list all available local tags. That would help us to confirm that the Changesets command created tags.

**Comment by Andarist** [comment]
Then I'm not exactly sure what happens here because we immediately try to create a tag after logging the "New tag" thing:
https://github.com/changesets/changesets/blob/8c0846977597ddaf51aaeb35f1f0f9428bf8ba14/packages/cli/src/commands/publish/index.ts#L127-L128

Perhaps something wrong happens in the tagging function itself - but that one just calls to `git`. Maybe you should try to log both stdout and stderr here?
https://github.com/changesets/changesets/blob/8c0846977597ddaf51aaeb35f1f0f9428bf8ba14/packages/git/src/index.ts#L46

**Comment by IPWright83** [comment]
Hey, just to check - your suggesting forking and adding a little more logging in?

**Comment by Andarist** [comment]
[`patch-package`](https://github.com/ds300/patch-package) is great for this sort of thing.

**Comment by IPWright83** [comment]
Hmm, I'm struggling to patch unfortunately :( I'm using `pnpm` and the patch-commit is failing with an error, and `patch-package` doesn't work with `pnpm` as it should be redundant. Somewhat frustrating!

**Comment by Andarist** [comment]
I think that pnpm has this as a bultin feature - https://pnpm.io/cli/patch

**Comment by IPWright83** [comment]
It does, turns out it doesn't work well on Windows. Was fine in my Ubuntu machine. Logging stderr was helpful

```
@chart-it@1.0.0 changeset /home/runner/work/chart-it/chart-it
> changeset "tag"

🦋  New tag:  react-demo@0.1.5
stdout: 
stderr: Committer identity unknown

*** Please tell me who you are.
```

**Comment by Andarist** [comment]
This is very useful info! And a clear sign that we should actually throw an error there because this is a clear error that should be surfaced asap. 

Could you share your workflow file with me?

**Comment by IPWright83** [comment]
Sure, it's currently public - https://github.com/IPWright83/chart-it/blob/master/.github/workflows/push-to-master.yml#L170

**Comment by IPWright83** [comment]
Sorry, as I'm actively fixing it

```
 publish:
    runs-on: ubuntu-latest
    needs: changesets_version
    # This will only run if there were no changesets.
    ## the next triggered build from the push will then pass this step and continue with the release
    if: always() && needs.changesets_version.outputs.changes == 'false'
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
          scope: "@<scope>"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: pnpm/action-setup@v2.2.2
        with:
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: pnpm Install
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Create Tags
        run: pnpm changeset tag
      - name: Tag debug
        run: git tag
      - name: Push tags
        run: git push --follow-tags
      - name: Release packages
        run: pnpm publish -r --access=public
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
```

**Comment by IPWright83** [comment]
Managed to get it working with some extra `git config` :) Thanks for the help.

I'd be interested (appreciate this is a tangent) to know if there's a way to get the "CHANGELOG" information into a tag? I was expecting something like this:

![image](https://user-images.githubusercontent.com/1374775/194711443-8e347228-3d99-4ba8-bf5f-7711d6a7aa6c.png)

But I just got 

![image](https://user-images.githubusercontent.com/1374775/194711463-3f08e95e-7e2d-4fa1-baef-cd1dfa16ffc5.png)

Despite the changelog having the information?

![image](https://user-images.githubusercontent.com/1374775/194711483-8da86250-c174-4103-aeec-0d02d7c1fa23.png)

**Comment by Andarist** [comment]
Oh, so you are not using our `changesets/action` and thus the git wasn't set up properly (I assume, I didn't quite test our action on Windows).

> I'd be interested (appreciate this is a tangent) to know if there's a way to get the "CHANGELOG" information into a tag? I was expecting something like this:

**I think** that since you are not using our actions those releases that you see are just auto-created by GitHub and thus they don't have content associated with them. `changeset tag` literally just git tag things - GitHub releases are created (based on git tags) by our `changesets/action` (but you are not using it)

**Comment by IPWright83** [comment]
Ah, I'm using the version command in a different step:

```
name: changeset version
        id: version
        run: echo ::set-output name=changes::$(pnpm bump 2>&1 | grep -q 'No unreleased changesets found' && echo 'false' || echo 'true')
      - name: Update lockfile
        if: steps.version.outputs.changes == 'true'
        run: pnpm install --no-frozen-lockfile
```

Have I just completely failed to set this up correctly? I thought I'd followed the docs correctly :(

**Comment by Andarist** [comment]
What I mean is that you interact with the CLI on your own - and unfortunately, this doesn't contain any logic for creating GitHub releases. This part lives (currently) in the [`changesets/action`](https://github.com/changesets/action). I think that we probably need to move some responsibilities around and rearchitect how this works to make this more flexible - there are already some open issues about this.

**Comment by IPWright83** [comment]
Ah ok gotcha. Thinking about it I had issues publishing and the author of pnpm showed me this way (which I think is how they do it).

Could you point me to any logic I could borrow until things have been updated to auto generate tag messages?

**Comment by IPWright83** [comment]
I'm trying to use the [changeset/action](https://github.com/changesets/action) now instead to get this working. However now I don't get the tag either. I'm assuming I'm missing some steps? Would you be able to take a quick look? I'm finding it really difficult to get changesets configured, but I really like the idea so want to get this working!

I'm currently using this:
```
  changesets_version:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    outputs:
      published: ${{ steps.version.release.published }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.2.2
        with:
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: pnpm Install
        run: pnpm install
      - name: Release
        id: release
        uses: changesets/action@v1
        with:
          publish: pnpm run publish
          version: pnpm run version
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  changesets_output_test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ changesets_version.outputs.changes }}
```

Where my root `package.json` contains:

```
"scripts" : {
    "version": "changeset version",
    "publish": "pnpm publish --filter @chart-it/react-d3"
}
```
